### ISSUE TITLE
errors merge when loading the local data package descriptor

### ISSUE THREAD

**Issue by wengdanyu** [frictionlessdata/datapackage-py#159]
import datapackage
package = datapackage.Package('datapackage.json')

error message like that:
return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 11841: illega
l multibyte sequence

**Comment by wengdanyu** [comment]
datapackage.json exits and  is valid

**Comment by roll** [comment]
@wengdanyu 
Thanks. Please provide the full error traceback like:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/roll/projects/datapackage-py/tmp/resource.py", line 24, in <module>
    resource.read(keyed=True)
  File "/home/roll/projects/datapackage-py/datapackage/resource.py", line 176, in read
    return self.__get_table().read(relations=relations, **options)
  File "/home/roll/projects/datapackage-py/.python/lib/python3.5/site-packages/tableschema/table.py", line 133, in read
    for count, row in enumerate(rows, start=1):
  File "/home/roll/projects/datapackage-py/.python/lib/python3.5/site-packages/tableschema/table.py", line 80, in iter
    for row_number, headers, row in iterator:
  File "/home/roll/projects/datapackage-py/.python/lib/python3.5/site-packages/tableschema/table.py", line 189, in builtin_processor
    row = self.__schema.cast_row(row)
  File "/home/roll/projects/datapackage-py/.python/lib/python3.5/site-packages/tableschema/schema.py", line 156, in cast_row
    raise exceptions.CastError(message, errors=errors)
tableschema.exceptions.CastError: There are 1 cast errors (see exception.errors)
```

**Comment by roll** [comment]
NOT-CONFIRMED
Please re-open if there will be more information to reproduce the error.
