### ISSUE TITLE
push_datapackage does not support url as location specifier

### ISSUE THREAD

**Issue by sirex** [frictionlessdata/datapackage-py#81]
``` python
import sqlalchemy as sa
import datapackage

engine = sa.create_engine('sqlite://')
descriptor = 'https://github.com/vilnius/transportas-velavimai/raw/master/datapackage.json'
datapackage.push_datapackage(descriptor, 'sql', engine=engine)
```

This throws following error:

``` pytb
Traceback (most recent call last):
  File "test_sql.py", line 8, in test_sql
    datapackage.push_datapackage(descriptor, 'sql', engine=engine)
  File "datapackage-py/datapackage/pushpull.py", line 51, in push_datapackage
    table = mappers.convert_path(resource.metadata['path'], name)
KeyError: 'path'
```

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/132

Current `push/pull_datapackage` API will not be fixed. There will be an updated API to solve this problem. Merging this issue to general re-implementation tracker.
