### ISSUE TITLE
push_datapackage does not support pushing inline data

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-py#84]
```
import datapackage
from sqlalchemy import create_engine
from datapackage import push_datapackage

dp = datapackage.DataPackage()
dp.metadata['name'] = 'my_sleep_duration'
dp.metadata['resources'] = [
    {'name': 'data'}
]

resource = dp.resources[0]
resource.metadata['data'] = [
    7, 8, 5, 6, 9, 7, 8
]

engine = create_engine('sqlite:///push-inline-data.db')
push_datapackage(descriptor=dp.metadata,backend='sql',engine=engine)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dan/open_knowledge/envs/world_gdp/lib/python3.5/site-packages/datapackage/pushpull.py", line 51, in push_datapackage
    table = mappers.convert_path(resource.metadata['path'], name)
KeyError: 'path'
```

Related to #81?

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/132

Current `push/pull_datapackage` API will not be fixed. There will be an updated API to solve this problem. Merging this issue to general re-implementation tracker.
